Repository zulip/zulip-terminal, pull requests merged in 2019-04, with the labels that each got.

#337 Undoing thumbs-up reaction now always works.
  zulipterminal/model.py
Labels: size: S

#345 BUGFIX: Fix sending to multiple recipients when narrowed.
  CHANGELOG.md
  zulipterminal/model.py
Labels: bug, size: S

#349 Display a hint when the user tries to select text with mouse
  zulipterminal/ui_tools/boxes.py
Labels: size: S

#353 core: Fix action of 'z' on self-messages.
  zulipterminal/core.py
Labels: size: XS
