Repository zulip/zulip-terminal, pull requests merged in 2019-03, with the labels that each got.

#314 Support #fff style for stream colors on older zulip servers
  CHANGELOG.md
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/buttons.py
Labels: bug, size: M

#321 requirements: Explicitly install tornado ~5.1 for snakeviz on py 3.4.
  Pipfile
  requirements.txt
  setup.py
Labels: size: XS

#318 Clarify Organization URL (was Realm URL) with examples.
  zulipterminal/cli/run.py
Labels: size: S

#317 keys: convert KEY_BINDINGS from Dict to OrderedDict.
  zulipterminal/config/keys.py
Labels: size: XL

#327 Model: Consolidate register calls & improve error handling
  zulipterminal/model.py
Labels: size: L
