Repository zulip/zulip-terminal, pull requests merged in 2019-02, with the labels that each got.

#292 Fix quoting original message, not rendered version
  CHANGELOG.md
  zulipterminal/ui_tools/boxes.py
Labels: bug, next major release, size: XS

#295 Improve inline item rendering
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: size: S

#296 help: Allow '?' to show/hide (toggle) help view, not just show it.
  CHANGELOG.md
  README.md
  zulipterminal/config/keys.py
  zulipterminal/core.py
  zulipterminal/ui_tools/views.py
Labels: size: S

#269 Improve Installation notes for users & developers
  README.md
Labels: size: L

#298 Compact the HelpView.
  zulipterminal/core.py
  zulipterminal/ui_tools/views.py
Labels: size: XS

#301 Improve help menu: compact further, style lines, adapt height
  CHANGELOG.md
  zulipterminal/core.py
  zulipterminal/ui_tools/views.py
Labels: size: S

#271 Error handling and other small fixes in run.py
  zulipterminal/cli/run.py
Labels: size: M

#285 cli: Add functionality to check version from command line. Fixes #280
  tests/cli/test_run.py
  zulipterminal/cli/run.py
Labels: size: M

#305 model/append_message: Set proper flags for received messages.
  tests/model/test_model.py
  zulipterminal/model.py
Labels: size: M

#312 Improve unread counts (refactor/simplify & fix few bugs)
  zulipterminal/helper.py
Labels: size: M
