Repository zulip/zulip-terminal, pull requests merged in 2019-01, with the labels that each got.

#243 README: Remove installation numbered steps; Improve zuliprc detail.
  README.md
Labels: enhancement

#255 BUGFIX: boxes: Avoid crash in soup2markup with empty content/soup.
  CHANGELOG.md
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: bug, high priority

#257 run: Set encoding to 'utf-8' at the start.
  CHANGELOG.md
  zulipterminal/cli/run.py
Labels: size: XS

#263 keys: Add `ctrl+d` as keyboard shortcut for sending a message.
  CHANGELOG.md
  README.md
  zulipterminal/config/keys.py
Labels: size: S

#267 Allow 'P' and 'f' keys to work from side panels
  CHANGELOG.md
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
Labels: UI, size: S

#270 changelog: Summarize recent changes not included in commits/PRs.
  CHANGELOG.md
Labels: size: S

#252 view: Fix support for HotKeys in new streams.
  zulipterminal/ui_tools/views.py
Labels: size: M

#277 themes: Add new styles to incomplete themes.
  tests/config/test_themes.py
  zulipterminal/config/themes.py
Labels: size: L
