Repository zulip/zulip-terminal, pull requests merged in 2019-08, with the labels that each got.

#462 core: Avoid writing newline to stdout after UI has loaded.
  zulipterminal/core.py
Labels: bug, high priority, size: XS

#465 bugfx: buttons: Fix marking 'M' in muted topics.
  zulipterminal/ui_tools/buttons.py
Labels: size: XS

#466 bugfix: model: Fix is_muted_topic helper using list instead of tuples.
  tests/model/test_model.py
  zulipterminal/model.py
Labels: size: S

#373 State support for PyPy, and test on pypy3.5
  .travis.yml
  Pipfile
  README.md
  setup.py
Labels: enhancement, feedback wanted, size: S
