Repository zulip/zulip-terminal, pull requests merged in 2019-06, with the labels that each got.

#390 model: Use event callback mapping when registering desired events
  zulipterminal/model.py
Labels: size: M

#378 themes/buttons: Set background color as default provided by terminal.
  zulipterminal/config/themes.py
  zulipterminal/ui_tools/buttons.py
Labels: size: M

#369 Switch to no-autohide view by default
  README.md
  tests/cli/test_run.py
  zulipterminal/cli/run.py
Labels: size: S

#396 bugfix: Avoid crash on 'ctrl 4' by ignoring quit character
  zulipterminal/core.py
Labels: bug, size: XS

#342 boxes: Reduce message padding after introduction of (EDITED).
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: size: S
