Repository zulip/zulip-terminal, pull requests merged in 2020-02, with the labels that each got.

#500 requirements: Update Urwid from 2.0.1 to 2.1.0.
  Pipfile
  requirements.txt
  setup.py
Labels: size: S

#502 tools: Use pycodestyle in place of outdated pytest-pep8.
  .travis.yml
  Pipfile
  README.md
  requirements.txt
  setup.cfg
  setup.py
  tests/conftest.py
  zulipterminal/model.py
Labels: size: L

#504 tools: Add tools/lint-all script to simplify local linting.
  README.md
  tools/lint-all
Labels: size: M

#507 Type Annotations: Use Message type alias consistently
  zulipterminal/core.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/utils.py
  zulipterminal/ui_tools/views.py
Labels: size: M

#505 refactor: Simplify unnecessarily complex super(...) calls.
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/buttons.py
  zulipterminal/ui_tools/views.py
Labels: size: L

#510 views: Fix stream and topic search.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: bug, size: M

#481 Report reasons for initial connection failure
  tests/model/test_model.py
  zulipterminal/model.py
Labels: size: XL
