Repository zulip/zulip-terminal, pull requests merged in 2020-04, with the labels that each got.

#568 Minor theme improvements
  zulipterminal/config/themes.py
Labels: UI, feedback wanted, size: S

#556 refactor: helper: Separate setting counts for model & UI.
  zulipterminal/helper.py
Labels: size: L

#584 Message reactions: Add spacing and refactor
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: M

#594 README/helper: Support notification sound for OSX.
  README.md
  zulipterminal/helper.py
Labels: size: S

#597 setup: Minor adjustments (remove license, adjust some text).
  setup.py
Labels: size: XS

#600 Refactor model event handling methods
  tests/model/test_model.py
  zulipterminal/model.py
Labels: size: XL

#610 themes: Add 256-color support to default theme.
  zulipterminal/config/themes.py
Labels: size: XL

#619 tests: Add command keys for exit popup keypress tests.
  tests/ui/test_ui_tools.py
Labels: size: S, tests (pytest)

#626 cleanup: Results of pyupgrade with --py3-only --keep-percent-format.
  zulipterminal/config/themes.py
  zulipterminal/core.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/tables.py
  zulipterminal/ui_tools/views.py
Labels: size: XL

#625 Use right-triangle symbol to separate stream & topic.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: S

#627 README: Update installation, running & configuration notes.
  README.md
Labels: needs review, size: L
