Repository zulip/zulip-terminal, pull requests merged in 2020-08, with the labels that each got.

#738 Check validity of recipients on manual modification
  zulipterminal/model.py
  zulipterminal/ui_tools/boxes.py
Labels: size: M

#761 bugfix: helper: Check view is rendered before displaying errors.
  zulipterminal/helper.py
Labels: size: XS

#760 Split API call and traceback logging into different log files
  .gitignore
  zulipterminal/cli/run.py
Labels: needs review, size: M

#750 Delegate link text for raw links in a better way
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: message rendering, needs review, size: M

#771 Show time mentions (with source text) in MsgInfoView
  tests/ui/test_ui_tools.py
  zulipterminal/core.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/views.py
Labels: PR needs review, size: S

#758 Move unread_count from StreamButton updates to Model.
  tests/model/test_model.py
  tests/ui/test_ui_tools.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui_tools/buttons.py
Labels: PR needs review, size: L

#787 Add an explore mode to run the app without marking messages as read
  README.md
  tests/cli/test_run.py
  tests/core/test_core.py
  tests/ui/test_ui_tools.py
  zulipterminal/cli/run.py
  zulipterminal/core.py
  zulipterminal/ui_tools/views.py
Labels: PR needs review, enhancement, further discussion required, size: M

#789 FAQ: Add entry discussing when messages are marked as read.
  docs/FAQ.md
Labels: PR needs review, documentation, size: S
