Repository zulip/zulip-terminal, pull requests merged in 2020-05, with the labels that each got.

#632 linting: Support pycodestyle E226 (arithmetic spacing)
  setup.cfg
  tests/config/test_themes.py
  tests/conftest.py
  tests/core/test_core.py
  tests/model/test_model.py
  tests/ui/test_ui_tools.py
  tests/ui_tools/test_boxes.py
  zulipterminal/core.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/buttons.py
  zulipterminal/ui_tools/views.py
Labels: needs review, size: L

#641 bugfix: views: Ensure focus returns to previous topic after search.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: needs review, size: M

#634 Use bullet character in list & remove newlines.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: M

#643 bugfix: TopicsView: Focus Frame header (search box) on search.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: size: XS

#612 themes/run: Rename themes & add compatibility aliases.
  tests/cli/test_run.py
  tests/config/test_themes.py
  zulipterminal/cli/run.py
  zulipterminal/config/themes.py
Labels: size: M

#640 tools/lister: Remove six dependency
  tools/lister.py
Labels: size: XS

#635 Don't corrupt screen if notifying fails; indicate to user once instead
  zulipterminal/core.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui_tools/views.py
Labels: needs review, size: L

#644 Render ordered lists
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: S

#645 Indicate panel searches in progress
  tests/ui_tools/test_boxes.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: L

#649 Render nested lists
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: enhancement, needs review, size: L

#656 Improve monochrome rendering of narrows & streams.
  zulipterminal/config/themes.py
  zulipterminal/ui_tools/buttons.py
Labels: size: S

#657 Colored recipient bars
  tests/ui/test_ui_tools.py
  zulipterminal/config/themes.py
  zulipterminal/ui_tools/boxes.py
Labels: size: L

#672 Ensure recipient headers are shown in message list
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: UI, bug, size: S
