Repository zulip/zulip-terminal, pull requests merged in 2020-03, with the labels that each got.

#534 tests: Parameterize hard-coded keys used in keypress tests.
  tests/ui/test_ui_tools.py
Labels: size: S

#537 views: Reset search box text when 'esc' is pressed.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/views.py
Labels: GSoC, bug, needs review, size: S

#554 boxes: Merge date/time and optional prev-year fields to improve styling.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: M

#553 light theme: Improve selections, quotes, stars & times.
  zulipterminal/config/themes.py
Labels: needs review, size: S

#564 Improve users panel theming (light, blue)
  zulipterminal/config/themes.py
Labels: size: S

#565 Improve consistency of selection styles
  zulipterminal/config/themes.py
Labels: size: S
