Repository zulip/zulip-terminal, pull requests merged in 2020-07, with the labels that each got.

#706 bugfix: helper: Avoid updating unread count for unsubscribed streams.
  zulipterminal/helper.py
Labels: bug, high priority, size: XS

#705 Visually separate pinned and unpinned streams while searching
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: UI, enhancement, size: L

#542 boxes: Improve trigger sequence for generic_autocomplete
  tests/ui_tools/test_boxes.py
  zulipterminal/ui_tools/boxes.py
Labels: needs review, size: L

#630 Refactoring focusing on tidying/migrating msg_list & msg_view
  tests/core/test_core.py
  tests/model/test_model.py
  tests/ui/test_ui.py
  tests/ui/test_ui_tools.py
  zulipterminal/core.py
  zulipterminal/model.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/views.py
Labels: needs review, size: XL

#734 docs: Update obsolete relative links in getting-started.md
  docs/getting-started.md
Labels: size: XS

#741 Move unicode characters to new file
  zulipterminal/config/symbols.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/views.py
Labels: size: M

#735 Support footlinks configuration via zuliprc
  README.md
  tests/cli/test_run.py
  tests/core/test_core.py
  tests/ui/test_ui_tools.py
  zulipterminal/cli/run.py
  zulipterminal/core.py
  zulipterminal/ui_tools/boxes.py
Labels: further discussion required, needs review, size: M
