Repository zulip/zulip-terminal, pull requests merged in 2021-02, with the labels that each got.

#902 refactor:Extract function for message being in a narrow
  zulipterminal/model.py
Labels: PR soon to be merged, area: refactoring, feedback wanted, size: L

#906 bugfix: boxes: Ensure self-message recipient_ids are a list.
  zulipterminal/ui_tools/boxes.py
Labels: PR soon to be merged, bug, size: S

#909 Remove space to split recipients by ','.
  tests/ui_tools/test_boxes.py
  zulipterminal/ui_tools/boxes.py
Labels: size: M

#910 refactor: Move from type comments to inline type annotations.
  tests/config/test_keys.py
  tests/ui_tools/test_buttons.py
  zulipterminal/cli/run.py
  zulipterminal/config/keys.py
  zulipterminal/config/themes.py
  zulipterminal/core.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/tables.py
  zulipterminal/ui_tools/utils.py
  zulipterminal/ui_tools/views.py
Labels: area: refactoring, size: XL

#924 refactor: Clarify draft types & naming
  zulipterminal/api_types.py
  zulipterminal/core.py
  zulipterminal/model.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
Labels: size: L

#904 Remove dead code in load_old_messages & simplify tests.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: size: M

#931 bugfix: core: Fix ZT crash due to AttributeErrors.
  zulipterminal/core.py
Labels: size: XS
