Repository zulip/zulip-terminal, pull requests merged in 2021-06, with the labels that each got.

#1043 README/docs: Fix minor typographical errors to improve readability
  README.md
  docs/FAQ.md
  docs/getting-started.md
Labels: size: S

#1031 README: Add Install subsection for keeping up to date.
  README.md
Labels: area: documentation, size: S

#1044 bugfix: ui: Focus on content_area when draft is opened from side-panels.
  tests/ui/test_ui.py
  zulipterminal/ui.py
Labels: PR needs review, size: L

#1054 bugfix: Construct narrow appropriately before verifying and triggering footer notifications.
  tests/helper/test_helper.py
  zulipterminal/helper.py
Labels: size: S

#1022 refactor: Simplify msg template generation in conftest using factory fixtures.
  tests/conftest.py
Labels: PR blocks other PR, PR needs review, size: XL

#978 view: Fix focus index before and after Panel Search.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: PR needs review, PR soon to be merged, bug, size: XL

#1017 docs: Add autocomplete info section in FAQ.
  docs/FAQ.md
Labels: PR needs review, area: documentation, size: M

#1055 README: Split out Commit Style notes into an expanded section.
  README.md
Labels: area: documentation, size: M
