Repository zulip/zulip-terminal, pull requests merged in 2021-07, with the labels that each got.

#1056 bugfix: Fix topic editing if topic unchanged
  tests/ui/test_ui_tools.py
  tests/ui_tools/test_boxes.py
  zulipterminal/ui_tools/boxes.py
Labels: bug, high priority, size: L

#1024 Improve katex/math text rendering in ZT
  tests/ui/test_ui_tools.py
  zulipterminal/config/themes.py
  zulipterminal/themes/gruvbox.py
  zulipterminal/themes/zt_blue.py
  zulipterminal/themes/zt_dark.py
  zulipterminal/themes/zt_light.py
  zulipterminal/ui_tools/boxes.py
Labels: PR soon to be merged, area: message rendering, size: M

#1071 github: Add pull request template.
  .github/pull_request_template.md
Labels: area: infrastructure, feedback wanted

#1064 Use urwid Button features to simplify TopButton.
  tests/conftest.py
  tests/ui/test_ui.py
  tests/ui/test_ui_tools.py
  tests/ui_tools/test_buttons.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/buttons.py
  zulipterminal/ui_tools/views.py
Labels: PR needs review, area: UI, feedback wanted

#1081 refactor: buttons/core: Avoid using StreamButton as a popup parameter.
  tests/core/test_core.py
  tests/ui_tools/test_buttons.py
  zulipterminal/core.py
  zulipterminal/ui_tools/buttons.py
Labels: PR needs review, size: M

#1082 refactor: views: Make mouse scroll-speed in side-panels consistent.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: PR needs review, size: M

#1085 bugfix: boxes/ui: Display mouse selection_hint for entire `View`.
  zulipterminal/ui.py
  zulipterminal/ui_tools/boxes.py
Labels: area: UI, bug, mouse support (low priority), size: M

#1090 bugfix: views: Ensure EditModeView works with new frame-based popup.
  tests/ui_tools/test_popups.py
  zulipterminal/ui_tools/views.py
Labels: bug: crash, high priority, size: S

#1093 buttons: Ensure muted button text color is adjusted when selected.
  tests/ui_tools/test_buttons.py
  zulipterminal/ui_tools/buttons.py
Labels: size: S

#1057 boxes: Use indicator attribute to hold compose box status.
  tests/ui_tools/test_boxes.py
  zulipterminal/ui_tools/boxes.py
Labels: PR awaiting update, size: XL
