Repository zulip/zulip-terminal, pull requests merged in 2021-03, with the labels that each got.

#941 bugfix: keys/hotkeys: Revert minor changes to improve documentation.
  docs/hotkeys.md
  zulipterminal/config/keys.py
Labels: PR soon to be merged, bug, size: M

#939 tools: Modernize convert-unicode-emoji-data.
  tools/convert-unicode-emoji-data
Labels: size: M

#960 boxes: Prefill stream name when user presses `c` in stream/topic narrow.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: size: S

#958 bugfix: views: Restore functionality of keypress `n`.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: bug: crash, size: S
