Repository zulip/zulip-terminal, pull requests merged in 2021-05, with the labels that each got.

#1018 popup: core: Use linear scaling for small terminal sizes.
  tests/core/test_core.py
  zulipterminal/core.py
Labels: feedback wanted, size: M

#1020 Tidy up reaction tests (prep for reaction event improvements)
  tests/model/test_model.py
Labels: area: refactoring, area: tests, size: XL

#1032 cryptography requires Rust toolchain on Alpine Linux.
  docker/Dockerfile.alpine
Labels: size: XS

#1035 bugfix: boxes: Allow message body editing when limit doesn't exist.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: area: message editing, missing feature: user, size: L
