Repository zulip/zulip-terminal, pull requests merged in 2021-08, with the labels that each got.

#1100 Overlay side-panel in autohide mode.
  tests/ui/test_ui.py
  zulipterminal/ui.py
Labels: PR awaiting update, PR blocks other PR, size: XL

#1110 gruvbox: Change background of selected to dark blue.
  zulipterminal/themes/gruvbox.py
Labels: size: XS, area: colors/styles/themes

#946 boxes: Add support for renaming (no topic) messages.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/boxes.py
Labels: size: XL, PR needs review, area: message editing

#1116 Use urwid's CommandMap to manage navigational keys.
  tests/config/test_keys.py
  tests/conftest.py
  tests/ui/test_ui.py
  tests/ui_tools/test_popups.py
  zulipterminal/config/keys.py
  zulipterminal/ui.py
  zulipterminal/ui_tools/views.py
Labels: size: XL, PR needs review, area: refactoring

#1122 Improve print-debugging (no `flush=True` required; require `-d`/`--debug`)
  README.md
  tests/core/test_core.py
  zulipterminal/cli/run.py
  zulipterminal/core.py
Labels: size: L, area: documentation, area: infrastructure

#1132 [WIP] Support CPython 3.10
  .github/workflows/lint-and-test.yml
  setup.py
Labels: size: S, area: infrastructure
