Repository zulip/zulip-terminal, pull requests merged in 2022-04, with the labels that each got.

#1180 git: Add .mailmap file to deduplicate contributors.
  .mailmap
Labels: size: S, area: infrastructure

#1201 views: Avoid sending GO_BACK to duplicate child widgets unnecessarily.
  tests/ui/test_ui_tools.py
  zulipterminal/ui_tools/views.py
Labels: bug, size: S, PR blocks other PR, area: refactoring

#1194 Support 'Narrow to current compose box recipient'.
  docs/hotkeys.md
  tests/helper/test_helper.py
  zulipterminal/config/keys.py
  zulipterminal/helper.py
  zulipterminal/ui_tools/boxes.py
Labels: area: hotkeys, size: M, PR soon to be merged

#1192 README: Add notes on using auto-formatting tools.
  README.md
Labels: size: M, area: documentation, area: infrastructure

#1206 bugfix: core: Do not exit editor mode when narrowing.
  zulipterminal/core.py
Labels: bug, size: XS, feedback wanted
