Repository zulip/zulip-terminal, pull requests merged in 2022-03, with the labels that each got.

#1154 Updates documentation for 16 color names in THEMES_CONTRIBUTING.md
  zulipterminal/themes/THEME_CONTRIBUTING.md
Labels: size: S

#1157 FAQ/README/themes: Update documentation to reflect current themes.
  README.md
  docs/FAQ.md
  zulipterminal/config/themes.py
Labels: size: S, area: documentation

#1156 FAQ: Expand small terminal section to suggest scrolling long messages.
  docs/FAQ.md
Labels: size: XS, area: documentation

#1162 bugfix: model: Avoid creating empty messages from reaction events.
  tests/model/test_model.py
  zulipterminal/model.py
Labels: bug, high priority, size: S

#748 bugfix: ui: Do not update footer if new text is same as current.
  tests/ui/test_ui.py
  zulipterminal/ui.py
Labels: bug, size: S, PR soon to be merged

#1181 Bugfix to update stream marker/color on editing stream message
  zulipterminal/ui_tools/boxes.py
Labels: bug, size: S, PR soon to be merged, area: message editing
