Repository zulip/zulip-terminal, pull requests merged in 2023-11, with the labels that each got.

#1432 Configuring the Exit Confirmation Popup
  README.md
  tests/cli/test_run.py
  tests/core/test_core.py
  zulipterminal/cli/run.py
  zulipterminal/core.py
Labels: size: M, PR awaiting update

#1437 Updated the AboutView popup with Exit confirmation setting
  tests/ui_tools/test_popups.py
  zulipterminal/core.py
  zulipterminal/ui_tools/views.py
Labels: size: S, PR soon to be merged

#1438 docs: Add Alacritty to successfully run terminal list
  docs/FAQ.md
Labels: size: XS, area: documentation, PR soon to be merged
