Repository zulip/zulip-terminal, pull requests merged in 2023-03, with the labels that each got.

#1316 Documentation: Improve commit message style & Add section on Structuring Commits
  README.md
Labels: size: XL, area: documentation

#1320 Bugfix: Respect the server's choice of URL when fetching api key
  tests/cli/test_run.py
  zulipterminal/cli/run.py
Labels: bug, size: M

#1325 README: Add note regarding use of tools to synchronize source with docs.
  README.md
Labels: area: documentation, PR soon to be merged, area: infrastructure

#1328 Rename & invert behavior of tools/generate_hotkeys.py
  .github/workflows/lint-and-test.yml
  README.md
  docs/hotkeys.md
  tools/lint-all
  tools/lint-hotkeys
Labels: size: M, PR soon to be merged, area: infrastructure, area: refactoring

#1350 refactor: seperate displaybox and simplyfing text for hotkeys(Fixed #1339)
  tests/ui_tools/test_popups.py
  zulipterminal/ui_tools/views.py
Labels: area: UI, size: L, PR soon to be merged

#1357 pull_request_template: Update and improve PR template.
  .github/pull_request_template.md
Labels: size: L, area: infrastructure

#1363 lint-all: Reorder linting for faster development cycle.
  tools/lint-all
Labels: size: XS, PR soon to be merged, area: infrastructure
