Repository zulip/zulip-terminal, pull requests merged in 2023-04, with the labels that each got.

#1370 README/FAQ Restructuring
  README.md
  docs/FAQ.md
Labels: size: XL, area: documentation, PR soon to be merged

#1352 Refactor: change pm_with to pm-with
  tests/core/test_core.py
  tests/helper/test_helper.py
  tests/model/test_model.py
  tests/ui_tools/test_messages.py
  zulipterminal/helper.py
  zulipterminal/model.py
  zulipterminal/ui_tools/messages.py
Labels: size: L, PR soon to be merged, api migrations

#1385 autocomplete: Match topic search text against start of all words
  tests/conftest.py
  tests/ui_tools/test_boxes.py
  zulipterminal/helper.py
Labels: size: L, PR soon to be merged, area: autocomplete

#1389 README/editorconfig: Add .editorconfig to improve editing consistency.
  .editorconfig
  README.md
Labels: PR soon to be merged, area: infrastructure
