Repository zulip/zulip-terminal, pull requests merged in 2024-07, with the labels that each got.

#1517 Add manual cycling of random hints in footer
  docs/hotkeys.md
  tests/ui/test_ui.py
  zulipterminal/config/keys.py
  zulipterminal/ui.py
Labels: area: UI, area: hotkeys, size: M, PR needs mentor review

#1520 Create new help categories related to opening compose box
  docs/hotkeys.md
  zulipterminal/config/keys.py
Labels: size: L, PR needs review, area: popup: help

#1516 Group narrowing commands and improve descriptions
  docs/hotkeys.md
  zulipterminal/config/keys.py
Labels: size: L, PR ready to be merged

#1538 mailmap: Add entries for Niloth P & Sashank Ravipati.
  .mailmap
Labels: size: XS
