Repository zulip/zulip-terminal, pull requests merged in 2024-06, with the labels that each got.

#1509 gitlint: Add regex to ignore some long lines.
  .gitlint
Labels: size: XS, area: infrastructure

#1494 Improve the handling of editor actions as a help category
  docs/hotkeys.md
  zulipterminal/config/keys.py
Labels: size: XL, PR soon to be merged, area: popup: help

#1496 Standardize hotkey help text
  docs/hotkeys.md
  zulipterminal/config/keys.py
Labels: size: L, PR soon to be merged, area: popup: help
