Repository zulip/zulip-terminal, pull requests merged in 2024-05, with the labels that each got.

#1492 boxes/views: Adopt urwid_readline for all editors.
  zulipterminal/ui_tools/boxes.py
  zulipterminal/ui_tools/views.py
Labels: area: UI, size: XS

#1488 github: Add simple issue templates & configuration
  .github/ISSUE_TEMPLATE/01_crash.md
  .github/ISSUE_TEMPLATE/02_bug.md
  .github/ISSUE_TEMPLATE/03_parity.md
  .github/ISSUE_TEMPLATE/04_platform.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: size: XL, PR soon to be merged, area: infrastructure

#1500 bugfix: github: Adjust label yaml quoting syntax.
  .github/ISSUE_TEMPLATE/01_crash.md
  .github/ISSUE_TEMPLATE/02_bug.md
  .github/ISSUE_TEMPLATE/03_parity.md
  .github/ISSUE_TEMPLATE/04_platform.md
Labels: size: S, area: infrastructure
